apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: db
data:
  APP_COLOR: blue
  APP_MODE: dev
  CACHE_SIZE: "24"
  CACHE_MODE: "true"
  PORT_MODE: enable
  POSTGRES_USER: reza
  POSTGRES_PASSWORD: "@reza@123"
