apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-red
  namespace: dev
  labels:
    app: nginx-red
spec:
  replicas: 5
  selector:
    matchLabels:
      type: nginx-red
  template:
    metadata:
      labels:
        type: nginx-red
    spec:
      containers:
        - name: nginx-deploy-container
          image: nginx:1.20
          resources:
            requests:
              cpu: "10m"
              memory: "10M"
            limits:
              cpu: "20"
              memory: "15M"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "color"
                    operator: "In"
                    values:
                      - "red"
      
      tolerations:
        - key: "color"
          operator: "Equal"
          value: "red"
          effect: "NoSchedule"
                      # - "small"
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: "size"
      #               operator: "In"
      #               values:
      #                 - "large"
      #                 - "small"


      # nodeSelector:
      #   size: small        
      # tolerations:
      #   - key: "anisa"
      #     operator: "Equal"
      #     value: "edu"
      #     effect: "NoSchedule"
