apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dev
  labels:
    app: nginx
spec:
  replicas: 16
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      labels:
        type: front-end
    spec:
      containers:
        - name: nginx-deploy-container
          image: nginx:1.19
          # resources:
          #   requests:
          #     cpu: "10m"
          #     memory: "20Mi"
          #   limits:
          #     cpu: "1500m"
          #     memory: "1Gi"
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: "size"
      #               operator: "In"
      #               values:
      #                 - "large"
      #                 - "small"


      # nodeSelector:
      #   size: small        
      # tolerations:
      #   - key: "anisa"
      #     operator: "Equal"
      #     value: "edu"
      #     effect: "NoSchedule"
