apiVersion: v1
kind: Pod
metadata:
  name: liveness
  namespace: dev
spec:
  containers:
    - name: liveness-container
      image: busybox:1.36
      command:
        - /bin/sh
        - -c
        - |
          touch /tmp/healthy
          sleep 10
          rm -rf /tmp/healthy
          sleep 30
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 3
        periodSeconds: 1
        failureThreshold: 3

