apiVersion: v1
kind: Pod
metadata:
  name: nginx-liveness
  namespace: dev
spec:
  containers:
    - name: nginx
      image: nginx:1.20
      livenessProbe:
        exec:
          command:
            - /bin/bash
            - -c
            - |
              curl 127.0.0.1:8080
        initialDelaySeconds: 15
        periodSeconds: 1

