apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: dev
  labels:
    app: db
spec:
  containers:
    - name: debug-container
      image: postgres
      envFrom:
        - secretRef:
            name: app-secret
