apiVersion: v1
kind: Pod
metadata:
  name: pod-init
  namespace: dev
spec:
  volumes:
    - name: myvol
      emptyDir:
        sizeLimit: 10Mi
  initContainers:
    - name: config-creator
      image: alpine
      command:
        - /bin/sh
        - -c
        - |
          echo "$(date) here is your config " > /mnt/vol/init1.txt
          sleep 5

      volumeMounts:
        - name: myvol
          mountPath: /mnt/vol
    - name: git-cloner
      image: alpine
      command:
        - /bin/sh
        - -c
        - |
          echo "$(date) here is your git repo " > /mnt/vol/init2.txt
      volumeMounts:
        - name: myvol
          mountPath: /mnt/vol
  containers:
    - name: nginx
      image: nginx:1.20
      volumeMounts:
        - name: myvol
          mountPath: /mnt/vol
