apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: dev
spec:
  volumes:
    - name: config
      configMap:
        name: app-config
  containers:
    - name: nginx
      image: nginx:1.20
      volumeMounts:
        - name: config
          mountPath: /mnt/config
    - name: alpine
      image: alpine
      volumeMounts:
        - name: config
          mountPath: /mnt/myconfig
      command:
        - sleep
        - infinity

