apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: db
data:
  config.sh: |
    #!/bin/bash
    apt update
    apt install wget
    wget https://download.burux.com/index.html -O /usr/share/nginx/html/index.html
