apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: dev
spec:
  containers:
    - name: debug
      image: alpine
      command:

        - sh
        - -c
        - |
          echo hello reza
          ls /
          pwd
          sleep infinity
      env:
        - name: APP_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_USER            
      envFrom:
        - configMapRef:
            name: app-config
