apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol2
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Mi
  hostPath:
    path: /var/local/aaa2
  persistentVolumeReclaimPolicy: Recycle
