apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol3
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1000Mi
  hostPath:
    path: /var/local/aaa3
  persistentVolumeReclaimPolicy: Retain
