apiVersion: v1
kind: Pod
metadata:
  name: readiness
  namespace: dev
  labels:
    app: nginx-readiness
spec:
  containers:
    - name: readiness-container
      image: busybox:1.36
      command:
        - /bin/sh
        - -c
        - |
          while true; do
            touch /tmp/healthy
            sleep 10
            rm -rf /tmp/healthy
            sleep 30
          done
      readinessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 3
        periodSeconds: 1
        failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: readiness-svc
spec:
  selector:
    app: nginx-readiness
  ports:
    - port: 80
