apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anisa-roleBinding
  namespace: dev
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "Role"
  name: "anisa-role"
subjects:
  - apiGroup: "rbac.authorization.k8s.io"
    kind: "User"
    name: "reza"
